import type { NewsItem, NewsCategory } from '@trading-viewer/shared'

export const getMockNewsItems = (category: NewsCategory): NewsItem[] => {
  const baseItems: Record<NewsCategory, NewsItem[]> = {
    japan: [
      {
        uuid: 'mock-jp-1',
        title: 'Bank of Japan Maintains Ultra-Low Interest Rates Despite Inflation Pressures',
        publisher: 'Nikkei',
        link: '#',
        time: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
        logo: 'N',
      },
      {
        uuid: 'mock-jp-2',
        title: 'Toyota Reports Record Q3 Earnings on Strong Hybrid Vehicle Sales',
        publisher: 'Reuters',
        link: '#',
        time: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
        logo: 'R',
      },
      {
        uuid: 'mock-jp-3',
        title: 'SoftBank Vision Fund Posts First Profit in Six Quarters',
        publisher: 'Bloomberg',
        link: '#',
        time: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        logo: 'B',
      },
      {
        uuid: 'mock-jp-4',
        title: 'Japanese Semiconductor Stocks Surge on TSMC Expansion Plans',
        publisher: 'Nikkei',
        link: '#',
        time: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
        logo: 'N',
      },
      {
        uuid: 'mock-jp-5',
        title: 'Sony Raises Full-Year Forecast on PlayStation 5 Strong Sales',
        publisher: 'Financial Times',
        link: '#',
        time: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
        logo: 'FT',
      },
      {
        uuid: 'mock-jp-6',
        title: 'Yen Weakens to 150 Against Dollar as BOJ Keeps Policy Unchanged',
        publisher: 'Reuters',
        link: '#',
        time: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
        logo: 'R',
      },
    ],
    world: [
      {
        uuid: 'mock-world-1',
        title: 'Apple Unveils AI Strategy, Stock Jumps 5% in After-Hours Trading',
        publisher: 'CNBC',
        link: '#',
        time: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
        logo: 'C',
      },
      {
        uuid: 'mock-world-2',
        title: 'Microsoft Beats Earnings Estimates on Cloud Growth Acceleration',
        publisher: 'Bloomberg',
        link: '#',
        time: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
        logo: 'B',
      },
      {
        uuid: 'mock-world-3',
        title: 'Tesla Announces New Gigafactory in Mexico, Production to Start 2025',
        publisher: 'Reuters',
        link: '#',
        time: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        logo: 'R',
      },
      {
        uuid: 'mock-world-4',
        title: 'NVIDIA Becomes First Chipmaker to Reach $1.5 Trillion Market Cap',
        publisher: 'Financial Times',
        link: '#',
        time: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
        logo: 'FT',
      },
      {
        uuid: 'mock-world-5',
        title: 'Amazon Prime Day Sales Hit Record $12.7 Billion',
        publisher: 'MarketWatch',
        link: '#',
        time: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
        logo: 'MW',
      },
      {
        uuid: 'mock-world-6',
        title: 'Meta Platforms Announces $40B Share Buyback Program',
        publisher: 'CNBC',
        link: '#',
        time: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
        logo: 'C',
      },
    ],
    crypto: [
      {
        uuid: 'mock-crypto-1',
        title: 'Bitcoin Surges Past $45,000 on ETF Approval Speculation',
        publisher: 'CoinDesk',
        link: '#',
        time: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
        logo: 'CD',
      },
      {
        uuid: 'mock-crypto-2',
        title: 'Ethereum Upgrade "Dencun" Successfully Deployed on Mainnet',
        publisher: 'CoinTelegraph',
        link: '#',
        time: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
        logo: 'CT',
      },
      {
        uuid: 'mock-crypto-3',
        title: 'SEC Files Lawsuit Against Major Crypto Exchange for Securities Violations',
        publisher: 'Reuters',
        link: '#',
        time: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        logo: 'R',
      },
      {
        uuid: 'mock-crypto-4',
        title: 'MicroStrategy Purchases Additional 5,000 Bitcoin',
        publisher: 'Bloomberg',
        link: '#',
        time: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
        logo: 'B',
      },
      {
        uuid: 'mock-crypto-5',
        title: 'Solana Network Outage Resolved After 5 Hours of Downtime',
        publisher: 'CoinDesk',
        link: '#',
        time: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
        logo: 'CD',
      },
      {
        uuid: 'mock-crypto-6',
        title: 'Major Banks Launch Blockchain-Based Cross-Border Payment System',
        publisher: 'Financial Times',
        link: '#',
        time: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
        logo: 'FT',
      },
    ],
    general: [
      {
        uuid: 'mock-general-1',
        title: 'Fed Minutes Show Officials Debated Pace of Rate Cuts Amid Economic Uncertainty',
        publisher: 'Reuters',
        link: '#',
        time: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
        logo: 'R',
      },
      {
        uuid: 'mock-general-2',
        title: 'Tech Stocks Rally as AI Earnings Beat Expectations Across Major Players',
        publisher: 'Bloomberg',
        link: '#',
        time: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
        logo: 'B',
      },
      {
        uuid: 'mock-general-3',
        title: 'Oil Prices Surge 3% on Middle East Supply Concerns and OPEC+ Production Cuts',
        publisher: 'CNBC',
        link: '#',
        time: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        logo: 'C',
      },
      {
        uuid: 'mock-general-4',
        title: 'Dollar Strengthens Against Major Currencies as Bond Yields Continue to Rise',
        publisher: 'Financial Times',
        link: '#',
        time: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
        logo: 'FT',
      },
      {
        uuid: 'mock-general-5',
        title: 'Crypto Market Sees $2B Inflow as Bitcoin ETF Approval Hopes Rise',
        publisher: 'CoinDesk',
        link: '#',
        time: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
        logo: 'CD',
      },
      {
        uuid: 'mock-general-6',
        title: 'European Markets Open Higher on Strong Manufacturing Data from Germany',
        publisher: 'MarketWatch',
        link: '#',
        time: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
        logo: 'MW',
      },
    ],
  }

  return baseItems[category] || baseItems.general
}
